package com.company.database;

import com.company.database.dataObjects.History;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.LinkedList;

public class HistoryDBHandler extends SQLiteDBHandler{
    /**
     * Inserts a History object into the database.
     * @param history The history object that is to be inserted.
     * @return a int of the autogenerated key in the database or -1 in case of a database Error.
     */
    static void insertHistory(History history) {
        try {
            c = DBConnect.getConnection();
            insertHistoryQuery(history);

        } catch (Exception e) {
            e.printStackTrace();
        }finally {
            close();
        }
    }

    private static void insertHistoryQuery(History history) throws SQLException {
        prepStm = c.prepareStatement("INSERT INTO History VALUES (?, ?, ?, ?)");
        prepStm.setInt(2, history.getFoodItemid());
        prepStm.setTimestamp(3, Timestamp.valueOf(history.getUseDate()));
        prepStm.setInt(4, history.getAmount());
        prepStm.execute();
    }

    /**
     * Returns all History entries of specific FoodItem.
     * @param foodItemId The FoodItem id which is used to search corresponding History entries.
     * @return A LinkedList of all matching History entries.
     */
    static LinkedList<History> getHistoryOf(int foodItemId) {
        try {
            c = DBConnect.getConnection();
            ResultSet rs = getHistoryOfQuery(foodItemId);
            return getHistoryObjectListFrom(rs);
        }catch (Exception e) {
            e.printStackTrace();
            return null;
        }finally {
            close();
        }
    }

    private static ResultSet getHistoryOfQuery(int foodItemId) throws SQLException {
        prepStm = c.prepareStatement("SELECT * FROM History WHERE FoodItemId = ? ORDER BY useDate");
        prepStm.setInt(1, foodItemId);
        return prepStm.executeQuery();
    }

    private static LinkedList<History> getHistoryObjectListFrom(ResultSet rs) throws SQLException {
        LinkedList<History> histories = new LinkedList<>();
        while (rs.next()) {
            histories.add(new History(
                    rs.getInt("id"),
                    rs.getInt("FoodItemId"),
                    rs.getTimestamp("useDate").toLocalDateTime(),
                    rs.getInt("amount")
            ));
        }
        return histories;
    }
    static void removeHistory(int foodItemId){
        try {
            c = DBConnect.getConnection();

            removeHistoryQuery(foodItemId);
        } catch (Exception e) {
            e.printStackTrace();
        }finally {
            close();
        }
    }

    private static void removeHistoryQuery(int foodItemId) throws SQLException{
        prepStm = c.prepareStatement("DELETE FROM History WHERE FoodItemId= ?");
        prepStm.setInt(1, foodItemId);
        prepStm.execute();
    }
}
