package com.company.database.dataObjects;

import java.time.LocalDateTime;
/**
 * @author Til-W
 * @version 1.0
 *
 */
public class History {

    private final int id;
    private final int foodItemid;
    private final LocalDateTime useDate;
    private final int amount;

    /**
     * Represents a History event and always has a associated FoodItem
     * @param id            Id which is autogenerated by the database if object is created before its
     *                      saved in the database the id is to be -1.
     * @param foodItemid    Id of its associated FoodItem.
     * @param useDate       History event Timestamp.
     * @param amount        History event amount changed.
     */
    public History(int id, int foodItemid, LocalDateTime useDate, int amount) {
        this.id = id;
        this.foodItemid = foodItemid;
        this.useDate = useDate;
        this.amount = amount;
    }
    public History( int foodItemid, LocalDateTime useDate, int amount) {
        this.id = 0;
        this.foodItemid = foodItemid;
        this.useDate = useDate;
        this.amount = amount;
    }

    public int getId() {
        return id;
    }

    public int getFoodItemid() {
        return foodItemid;
    }

    public LocalDateTime getUseDate() {
        return useDate;
    }

    public int getAmount() {
        return amount;
    }

    @Override
    public String toString() {
        return  "Id             : " + id + "\n"+
                "Date of Use    : " + useDate + "\n"+
                "Amount added   : " + amount + "\n\n";
    }
}




