package com.company.database.dataObjects;

/**
 * @author Til-W
 * @version 1.0
 *
 */
public class Ingredient {
    private final int id;
    private final String name;
    private final int amount;
    private final int recipeId;

    /**
     * Represents a Ingredient and always has a associated Recipe
     * @param id        Id which is autogenerated by the database if object is created before its
     *                  saved in the database the id is to be -1.
     * @param name      Ingredient name
     * @param amount    Ingredient amount
     * @param recipeId  Id of its associated Recipe
     */
    public Ingredient(int id, String name, int amount, int recipeId) {
        this.id = id;
        this.name = name;
        this.amount = amount;
        this.recipeId = recipeId;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getAmount() {
        return amount;
    }

    public int getRecipeId() {
        return recipeId;
    }

    @Override
    public String toString() {
        return name + ", " + amount;
    }
}
