package com.company.database.dataObjects;

/**
 * @author Til-W
 * @version 1.0
 *
 */
public class Recipe {
    private final int recipeId;
    private final String name;

    /**
     * Represents Recipe
     * @param recipeId  Id which is autogenerated by the database if object is created before its
     *                  saved in the database the id is to be -1.
     * @param name      Recipe name.
     */
    public Recipe(int recipeId, String name) {
        this.recipeId = recipeId;
        this.name = name;
    }
    public Recipe(String name) {
        this.recipeId = -1;
        this.name = name;
    }


    public int getRecipeId() {
        return recipeId;
    }

    public String getName() {
        return name;
    }

    public String toString() {

        return name;
    }
}
